// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appupdate} from '../models';
import {httpdownload} from '../models';
import {main} from '../models';
import {vpnprofile} from '../models';

export function CaptureScreen():Promise<string>;

export function CheckForUpdate(arg1:string):Promise<appupdate.Result>;

export function CheckReceivedFiles(arg1:string,arg2:Array<httpdownload.FileInfo>):Promise<Array<main.ReceivedFileState>>;

export function ClearTaskbarProgress():Promise<void>;

export function GeneratePassword():Promise<string>;

export function IsAdministrator():Promise<boolean>;

export function LoadVPNProfiles():Promise<vpnprofile.Store>;

export function OpenSaveDir(arg1:string):Promise<string>;

export function RemoteFiles(arg1:string):Promise<main.RemoteListResponse>;

export function RevealReceivedFile(arg1:string,arg2:httpdownload.FileInfo):Promise<void>;

export function SaveVPNProfiles(arg1:vpnprofile.Store):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetTaskbarProgress(arg1:number,arg2:number):Promise<void>;

export function StartHTTPDownload(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:Array<httpdownload.FileInfo>,arg6:boolean,arg7:number):Promise<void>;

export function StartTransfer(arg1:main.TransferRequest):Promise<void>;

export function StartupSharePaths():Promise<Array<string>>;

export function Status():Promise<main.AppStatus>;

export function StopHTTPDownload():Promise<void>;

export function StopTransfer(arg1:string):Promise<void>;

export function UpdateSharePaths(arg1:Array<string>):Promise<void>;
