// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function LocateGonc(arg1) {
  return window['go']['main']['App']['LocateGonc'](arg1);
}

export function RemoteFiles(arg1) {
  return window['go']['main']['App']['RemoteFiles'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function StartHTTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartHTTPDownload'](arg1, arg2, arg3);
}

export function StartTransfer(arg1) {
  return window['go']['main']['App']['StartTransfer'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopHTTPDownload() {
  return window['go']['main']['App']['StopHTTPDownload']();
}

export function StopTransfer() {
  return window['go']['main']['App']['StopTransfer']();
}
