// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen() {
  return window['go']['main']['App']['CaptureScreen']();
}

export function ClearTaskbarProgress() {
  return window['go']['main']['App']['ClearTaskbarProgress']();
}

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function IsAdministrator() {
  return window['go']['main']['App']['IsAdministrator']();
}

export function LoadVPNProfiles() {
  return window['go']['main']['App']['LoadVPNProfiles']();
}

export function RemoteFiles(arg1) {
  return window['go']['main']['App']['RemoteFiles'](arg1);
}

export function SaveVPNProfiles(arg1) {
  return window['go']['main']['App']['SaveVPNProfiles'](arg1);
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder(arg1) {
  return window['go']['main']['App']['SelectFolder'](arg1);
}

export function SetTaskbarProgress(arg1, arg2) {
  return window['go']['main']['App']['SetTaskbarProgress'](arg1, arg2);
}

export function StartHTTPDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartHTTPDownload'](arg1, arg2, arg3, arg4);
}

export function StartTransfer(arg1) {
  return window['go']['main']['App']['StartTransfer'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopHTTPDownload() {
  return window['go']['main']['App']['StopHTTPDownload']();
}

export function StopTransfer(arg1) {
  return window['go']['main']['App']['StopTransfer'](arg1);
}

export function UpdateSharePaths(arg1) {
  return window['go']['main']['App']['UpdateSharePaths'](arg1);
}
