// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vpnprofile} from '../models';
import {main} from '../models';

export function CaptureScreen():Promise<string>;

export function ClearTaskbarProgress():Promise<void>;

export function GeneratePassword():Promise<string>;

export function IsAdministrator():Promise<boolean>;

export function LoadVPNProfiles():Promise<vpnprofile.Store>;

export function RemoteFiles(arg1:string):Promise<main.RemoteListResponse>;

export function SaveVPNProfiles(arg1:vpnprofile.Store):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetTaskbarProgress(arg1:number,arg2:number):Promise<void>;

export function StartHTTPDownload(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<void>;

export function StartTransfer(arg1:main.TransferRequest):Promise<void>;

export function Status():Promise<main.AppStatus>;

export function StopHTTPDownload():Promise<void>;

export function StopTransfer(arg1:string):Promise<void>;

export function UpdateSharePaths(arg1:Array<string>):Promise<void>;
